import Foundation
import AppKit

@MainActor
public class ClipboardMonitor {
    public var onNewClip: ((ClipContent, String?) -> Void)?

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var ticker: Timer?

    private let ignoredTypePrefixes = ["dyn."]
    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    public init() {
        lastChangeCount = pasteboard.changeCount
        startPolling()
    }

    public init(testMode: Bool) {
        lastChangeCount = 0
    }

    private func startPolling() {
        ticker = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.checkPasteboard()
            }
        }
    }

    private func checkPasteboard() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        // Check for concealed/transient content — skip if present
        if let types = pasteboard.types {
            for type in types {
                let raw = type.rawValue
                if ignoredTypes.contains(raw) { return }
                if ignoredTypePrefixes.contains(where: { raw.hasPrefix($0) }) && types.count == 1 { return }
            }
        }

        let sourceApp = NSWorkspace.shared.frontmostApplication?.localizedName

        // Try text first
        if let string = pasteboard.string(forType: .string), !string.isEmpty {
            onNewClip?(.text(string), sourceApp)
            return
        }

        // Try image (PNG then TIFF)
        if let imageData = pasteboard.data(forType: .png) {
            onNewClip?(.image(imageData), sourceApp)
            return
        }
        if let tiffData = pasteboard.data(forType: .tiff),
           let image = NSImage(data: tiffData),
           let pngData = image.tiffRepresentation.flatMap({ NSBitmapImageRep(data: $0)?.representation(using: .png, properties: [:]) }) {
            onNewClip?(.image(pngData), sourceApp)
            return
        }
    }

    deinit {
        ticker?.invalidate()
    }
}
