import Foundation
import AppKit

@MainActor
public class ClipboardMonitor {
    public var onNewClip: ((ClipContent, String?) -> Void)?

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var ticker: Timer?

    private let ignoredTypePrefixes = ["dyn."]
    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    public init() {
        lastChangeCount = pasteboard.changeCount
        startPolling()
    }

    public init(testMode: Bool) {
        lastChangeCount = 0
    }

    private func startPolling() {
        ticker = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.checkPasteboard()
            }
        }
    }

    private func checkPasteboard() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        // Check for concealed/transient content — skip if present
        if let types = pasteboard.types {
            for type in types {
                let raw = type.rawValue
                if ignoredTypes.contains(raw) { return }
                if ignoredTypePrefixes.contains(where: { raw.hasPrefix($0) }) && types.count == 1 { return }
            }
        }

        let sourceApp = NSWorkspace.shared.frontmostApplication?.localizedName

        // Try text first
        if let string = pasteboard.string(forType: .string), !string.isEmpty {
            // Skip HTML source noise — if it looks like raw HTML tags, ignore it
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            if Self.looksLikeHTMLSource(trimmed) { return }
            onNewClip?(.text(string), sourceApp)
            return
        }

        // Try image (PNG then TIFF)
        if let imageData = pasteboard.data(forType: .png) {
            onNewClip?(.image(imageData), sourceApp)
            return
        }
        if let tiffData = pasteboard.data(forType: .tiff),
           let image = NSImage(data: tiffData),
           let pngData = image.tiffRepresentation.flatMap({ NSBitmapImageRep(data: $0)?.representation(using: .png, properties: [:]) }) {
            onNewClip?(.image(pngData), sourceApp)
            return
        }
    }

    /// Detect raw HTML source that shouldn't be stored as a useful clip
    private static func looksLikeHTMLSource(_ text: String) -> Bool {
        let lower = text.lowercased()
        // Starts with a tag or doctype
        if lower.hasPrefix("<!doctype") || lower.hasPrefix("<html") || lower.hasPrefix("<head") { return true }
        // HTML comments only
        if lower.hasPrefix("<!--") && lower.hasSuffix("-->") { return true }
        // Mostly tags: if >60% of content is inside angle brackets, it's HTML source
        let tagChars = text.filter { $0 == "<" || $0 == ">" }.count
        if text.count > 20 && Double(tagChars) / Double(text.count) > 0.1 {
            // Count actual tags
            let tagCount = text.components(separatedBy: "<").count - 1
            let lineCount = max(1, text.components(separatedBy: .newlines).count)
            if tagCount > lineCount * 2 { return true }
        }
        return false
    }

    deinit {
        ticker?.invalidate()
    }
}
